#!/usr/bin/env bash
set -e
script_dir=$(dirname $(readlink -f $0))
if ! test -f $script_dir/this_dir; then
  echo $script_dir > $script_dir/this_dir 
fi
cd $script_dir
source "$script_dir/env/bin/activate"
python -u cecdaemon.py  "${@:1}"